name: Deploy netlify site

jobs:
  build:
    runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v3
  - name: Setup NodeJS
    uses: actions/setup-node@v4
    with:
      node-version: 24
  - run: mkdir dist
  - uses: docker://pandoc/core:3.7.0.2-alpine
    with:
      args: >-
        --standalone
        --template=template.html
        --metadata=lang=en
        -M updated=$(date)
        -o ./src/output.html
        index.md
  - run: npm install netlify-cli@22.2.1 -g
  - run: netlify deploy --dir dist
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}